from django.urls import path

from . import views

urlpatterns = [
    path(
        "signup/",
        views.Signup.as_view(),
        name="signup",
    ),
    path(
        "signin/",
        views.SignIn.as_view(),
        name="signin",
    ),
    path(
        "signout/",
        views.Logout.as_view(),
        name="signout",
    ),
    path(
        "forgot-password/",
        views.ForgotPassword.as_view(),
        name="forgot_password",
    ),
    path(
        "change-password/",
        views.ChangePassword.as_view(),
        name="change_password",
    ),
    path(
        "designations/",
        views.Designations.as_view(),
        name="designations",
    ),
    path(
        "company-list/",
        views.Company.as_view(),
        name="company_list",
    ),
    path(
        "site-list/",
        views.Site.as_view(),
        name="site_list",
    ),
    path(
        "user-invite/",
        views.UserInvite.as_view(),
        name="user_invite",
    ),
    path(
        "resend-invite-mail/",
        views.ResendInviteMail.as_view(),
    ),
    path(
        "user-master/",
        views.UserMaster.as_view(),
        name="user_master",
    ),
    path(
        "toggle-user-site-mapping/",
        views.ToggleUserSiteMapping.as_view(),
        name="toggle_user_site_mapping",
    ),
    path(
        "export-to-csv/",
        views.ExportToCSV.as_view(),
        name="export_to_csv",
    ),
    path(
        "user-profile/",
        views.UserProfile.as_view(),
        name="user_profile",
    ),
    path(
        "email-verification/",
        views.EmailVerification.as_view(),
        name="email_verification",
    ),
    path(
        "site-preference/",
        views.UserProfileSitePreference.as_view(),
        name="site_preference",
    ),
    path(
        "user-profile-change-password/",
        views.UserProfileChangePassword.as_view(),
        name="user_profile_change_password",
    ),
    path(
        "upload-profile-pic/",
        views.UploadProfilePic.as_view(),
        name="upload_profile_pic",
    ),
]
